spring.application.name=${SPRING_APPLICATION_NAME}

app.backend-url=${APP_BACKEND_URL}
app.frontend-url=${APP_FRONTEND_URL}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update